/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jframes;

/**
 *
 * @author Lenovo
 */
public class VtnMostrarInfo extends javax.swing.JDialog
{

    /**
     * Creates new form VtnMostrarInfo
     */
    public VtnMostrarInfo(java.awt.Frame parent, boolean modal,
            String nombreA,String extension, String fechaCreacion,String autorArchi,String tipoArchivo,int tamanio,String ruta)
    {
        super(parent, modal);
        initComponents();
        jLabelA.setText(nombreA);
        jLabelEA.setText(extension);
        jLabelFC.setText(fechaCreacion);
        jLabelAA.setText(autorArchi);
        jLabelTA.setText(tipoArchivo);
        jLabelTamanio.setText(String.valueOf(tamanio));
        jLabelRA.setText(ruta);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTipoArch = new javax.swing.JLabel();
        jLabelRutaArchi = new javax.swing.JLabel();
        jLabelExtensionA = new javax.swing.JLabel();
        jLabelAutorArch = new javax.swing.JLabel();
        jLabelFechaCrea = new javax.swing.JLabel();
        jLabelNombreA = new javax.swing.JLabel();
        jLabelRA = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelEA = new javax.swing.JLabel();
        jLabelFC = new javax.swing.JLabel();
        jLabelAA = new javax.swing.JLabel();
        jLabelTA = new javax.swing.JLabel();
        jLabelTipoArch1 = new javax.swing.JLabel();
        jLabelTamanio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(220, 230, 244));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setText("Información del archivo...");
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabelTipoArch.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelTipoArch.setText("Tipo de archivo:");
        jPanelFondo.add(jLabelTipoArch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, -1));

        jLabelRutaArchi.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelRutaArchi.setText("Ruta del archivo:");
        jPanelFondo.add(jLabelRutaArchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 170, -1));

        jLabelExtensionA.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelExtensionA.setText("Extensión del archivo: ");
        jPanelFondo.add(jLabelExtensionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabelAutorArch.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelAutorArch.setText("Autor del archivo:");
        jPanelFondo.add(jLabelAutorArch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, -1));

        jLabelFechaCrea.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelFechaCrea.setText("Fecha de creación:");
        jPanelFondo.add(jLabelFechaCrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 190, -1));

        jLabelNombreA.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelNombreA.setText("Nombre del archivo: ");
        jPanelFondo.add(jLabelNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabelRA.setBackground(new java.awt.Color(132, 165, 214));
        jLabelRA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRA.setOpaque(true);
        jPanelFondo.add(jLabelRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 270, 30));

        jLabelA.setBackground(new java.awt.Color(132, 165, 214));
        jLabelA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelA.setOpaque(true);
        jPanelFondo.add(jLabelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 270, 30));

        jLabelEA.setBackground(new java.awt.Color(132, 165, 214));
        jLabelEA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEA.setOpaque(true);
        jPanelFondo.add(jLabelEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 270, 30));

        jLabelFC.setBackground(new java.awt.Color(132, 165, 214));
        jLabelFC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFC.setOpaque(true);
        jPanelFondo.add(jLabelFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 270, 30));

        jLabelAA.setBackground(new java.awt.Color(132, 165, 214));
        jLabelAA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAA.setOpaque(true);
        jPanelFondo.add(jLabelAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 270, 30));

        jLabelTA.setBackground(new java.awt.Color(132, 165, 214));
        jLabelTA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTA.setOpaque(true);
        jPanelFondo.add(jLabelTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 270, 30));

        jLabelTipoArch1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelTipoArch1.setText("Tamaño del archivo:");
        jPanelFondo.add(jLabelTipoArch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 190, -1));

        jLabelTamanio.setBackground(new java.awt.Color(132, 165, 214));
        jLabelTamanio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTamanio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTamanio.setOpaque(true);
        jPanelFondo.add(jLabelTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnMostrarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnMostrarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnMostrarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnMostrarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnMostrarInfo dialog = new VtnMostrarInfo(new javax.swing.JFrame(), true, "", "", "", "", "", 0,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelAA;
    private javax.swing.JLabel jLabelAutorArch;
    private javax.swing.JLabel jLabelEA;
    private javax.swing.JLabel jLabelExtensionA;
    private javax.swing.JLabel jLabelFC;
    private javax.swing.JLabel jLabelFechaCrea;
    private javax.swing.JLabel jLabelNombreA;
    private javax.swing.JLabel jLabelRA;
    private javax.swing.JLabel jLabelRutaArchi;
    private javax.swing.JLabel jLabelTA;
    private javax.swing.JLabel jLabelTamanio;
    private javax.swing.JLabel jLabelTipoArch;
    private javax.swing.JLabel jLabelTipoArch1;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
